# vim:fileencoding=utf-8:foldmethod=marker
# Tokyo Night theme for yazi file manager

# : Manager {{{

[mgr]
# Current working directory color (blue)
cwd = { fg = "#7aa2f7" }

# Hover effects
hovered         = { reversed = true }  # Reverse colors for hovered items
preview_hovered = { underline = true }  # Underline hovered items in preview

# Search highlighting
find_keyword  = { fg = "#f7768e", bold = true, italic = true, underline = true }  # Red for search terms
find_position = { fg = "#bb9af7", bg = "reset", bold = true, italic = true }  # Purple for search position

# File operation markers
marker_copied   = { fg = "#9ece6a", bg = "#9ece6a" }  # Green for copied files
marker_cut      = { fg = "#e0af68", bg = "#f7768e" }  # Yellow/Red for cut files
marker_marked   = { fg = "#7aa2f7", bg = "#7dcfff" }  # Blue for marked files
marker_selected = { fg = "#e0af68", bg = "#e0af68" }  # Yellow for selected files

# Counter appearance for file operations
count_copied   = { fg = "#1a1b26", bg = "#9ece6a" }  # Green background for copy count
count_cut      = { fg = "#1a1b26", bg = "#e0af68" }  # Yellow background for cut count
count_selected = { fg = "#1a1b26", bg = "#7aa2f7" }  # Blue background for selection count

# Border styling
border_symbol = "│"  # Vertical line character for borders
border_style  = { fg = "#414868" }  # Dark gray color for borders

# : }}}


# : Tabs {{{

[tabs]
# Tab appearance
active   = { fg = "#292e42", bg = "#7aa2f7", bold = true }  # Blue background for active tab
inactive = { fg = "#7aa2f7", bg = "#292e42" }  # Dark background for inactive tabs

# : }}}


# : Mode {{{

[mode]

# Normal mode
normal_main = { fg = "#292e42", bg = "#7aa2f7", bold = true }  # Blue background for normal mode
normal_alt  = { fg = "#7aa2f7", bg = "#292e42" }

# Select mode
select_main = { fg = "#292e42", bg = "#9ece6a", bold = true }  # Green background for select mode
select_alt  = { fg = "#7aa2f7", bg = "#292e42" }

# Unset mode
unset_main = { fg = "#292e42", bg = "#bb9af7", bold = true }  # Purple background for unset mode
unset_alt  = { fg = "#7aa2f7", bg = "#292e42" }

# : }}}


# : Status bar {{{

[status]
overall = { fg = "#7aa2f7" }  # Overall status bar color
sep_left  = { open = "", close = "" }  # Left separator symbols
sep_right = { open = "", close = "" }  # Right separator symbols


# Progress indicators
progress_label = { fg = "#292e42", bold = true }  # Progress label styling
progress_normal = { fg = "#7aa2f7", bg = "#292e42" }  # Normal progress bar
progress_error = { fg = "#f7768e", bg = "#292e42" }  # Error progress bar

# File permissions styling
perm_sep   = { fg = "#7aa2f7" }  # Permission separator
perm_type  = { fg = "#9ece6a" }  # File type permission
perm_read  = { fg = "#e0af68" }  # Read permission
perm_write = { fg = "#f7768e" }  # Write permission
perm_exec  = { fg = "#bb9af7" }  # Execute permission


# : }}}

# : Pick {{{

[pick]
# File picker styling
border = { fg = "#7aa2f7" }  # Picker border color
active = { fg = "#bb9af7", bold = true }  # Active picker item
inactive = {}  # Inactive picker items

# : }}}


# : Input {{{

[input]
# Input dialog styling
border   = { fg = "#7aa2f7" }  # Input border color
title    = {}  # Input title styling
value    = {}  # Input value styling
selected = { reversed = true }  # Selected input text

# : }}}


# : Completion {{{

[cmp]
# Completion dialog styling
border = { fg = "#7aa2f7" }  # Completion border color

# : }}}


# : Tasks {{{

[tasks]
# Task manager styling
border  = { fg = "#7aa2f7" }  # Task border color
title   = {}  # Task title styling
hovered = { fg = "#bb9af7", underline = true }  # Hovered task styling

# : }}}


# : Which {{{

[which]
# Help/keybinding popup styling
mask            = { bg = "#414868" }  # Background mask
cand            = { fg = "#9ece6a" }  # Command candidates
rest            = { fg = "#a9b1d6" }  # Rest of the text
desc            = { fg = "#bb9af7" }  # Command descriptions
separator       = "  "  # Separator between elements
separator_style = { fg = "#626880" }  # Separator styling

# : }}}


# : Help {{{

[help]
# Help dialog styling
on      = { fg = "#9ece6a" }  # Active help items
run     = { fg = "#bb9af7" }  # Runnable help items
hovered = { reversed = true, bold = true }  # Hovered help items
footer  = { fg = "#1a1b26", bg = "#a9b1d6" }  # Help footer

# : }}}


# : Notify {{{

[notify]
# Notification styling
title_info  = { fg = "#9ece6a" }  # Info notification title
title_warn  = { fg = "#f7768e" }  # Warning notification title
title_error = { fg = "#e0af68" }  # Error notification title

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#e0af68" },  # Yellow for images

	# Media
	{ mime = "video/*", fg = "#f7768e" },  # Red for videos
	{ mime = "audio/*", fg = "#f7768e" },  # Red for audio

	# Archives
	{ mime = "application/zip",             fg = "#bb9af7" },  # Purple for archives
	{ mime = "application/x-tar",           fg = "#bb9af7" },
	{ mime = "application/x-bzip*",         fg = "#bb9af7" },
	{ mime = "application/x-bzip2",         fg = "#bb9af7" },
	{ mime = "application/x-7z-compressed", fg = "#bb9af7" },
	{ mime = "application/x-rar",           fg = "#bb9af7" },
	{ mime = "application/x-xz",            fg = "#bb9af7" },

	# Documents
	{ mime = "application/doc",        fg = "#9ece6a" },  # Green for documents
	{ mime = "application/epub+zip",   fg = "#9ece6a" },
	{ mime = "application/pdf",        fg = "#9ece6a" },
	{ mime = "application/rtf",        fg = "#9ece6a" },
	{ mime = "application/vnd.*",      fg = "#9ece6a" },

	# Fallback
	{ name = "*", fg = "#c6d0f5" },  # Light gray for regular files
	{ name = "*/", fg = "#7aa2f7" }  # Blue for directories
]

# : }}}